### ISSUE TITLE
Have you tried this on the AMI dataset？

### ISSUE THREAD

**Issue by melttt** [hitachi-speech/EEND#18]
Great paper! I  like the idea. but I get a terrible result in AMI dataset(about 40+ der)。

**Comment by ChokJohn** [comment]
@hshota0530 I also try to reproduce on AMI by myself, and I also get a  terrible result. Could you share your pertrained model before adaption on AMI dataset or the final model on  AMI dataset? Thanks!

**Comment by shota-horiguchi** [comment]
You may have seen our arxiv preprint (https://arxiv.org/abs/2106.10654), but the codes in this repo are based on our INTERSPEECH 2020 paper. We have some updates from the INTERSPEECH version, so results on AMI will be very different since AMI mostly consists of four-speaker conversations. Now we are planning to release our new implementation based on the arxiv version.

**Comment by ChokJohn** [comment]
Thanks for your reply. Is it convenient for you to tell me what you plan to release your update? You don’t seem to update this repository often.

> You may have seen our arxiv preprint (https://arxiv.org/abs/2106.10654), but the codes in this repo are based on our INTERSPEECH 2020 paper. We have some updates from the INTERSPEECH version, so results on AMI will be very different since AMI mostly consists of four-speaker conversations. Now we are planning to release our new implementation based on the arxiv version.

**Comment by tjgraham** [comment]
@hshota0530 I'm also interested in seeing your new implementation running on AMI data, any timeline on when it might be released?
